############## server配置 #################
server:
  port: 9999

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  profiles:
    active: local
---
############ spring local ##########
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1/demo?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 991501pj
    initialSize: 5
    minIdle: 5
    maxActive: 30

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
mybatis:
  mapper-locations: classpath:**/*Mapper.xml
  #在控制抬打印出SQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #type-aliases-package: com.example.demo.model

#日志使用log4j
#logging:
#  config: classpath:log4j2.xml